//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrice.TreolanBase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/treolan/wsdl/", ConfigurationName="TreolanBase.WebServiceSoapPort")]
    public interface WebServiceSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCatalog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenCatalogResponse GenCatalog(ApiPrice.TreolanBase.GenCatalogRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCatalog", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCatalogResponse> GenCatalogAsync(ApiPrice.TreolanBase.GenCatalogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCatalogV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenCatalogV2Response GenCatalogV2(ApiPrice.TreolanBase.GenCatalogV2Request request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCatalogV2", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCatalogV2Response> GenCatalogV2Async(ApiPrice.TreolanBase.GenCatalogV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenStockResponse GenStock(ApiPrice.TreolanBase.GenStockRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenStock", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenStockResponse> GenStockAsync(ApiPrice.TreolanBase.GenStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenInvoiceResponse GenInvoice(ApiPrice.TreolanBase.GenInvoiceRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenInvoiceResponse> GenInvoiceAsync(ApiPrice.TreolanBase.GenInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenReserveList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenReserveListResponse GenReserveList(ApiPrice.TreolanBase.GenReserveListRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenReserveList", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenReserveListResponse> GenReserveListAsync(ApiPrice.TreolanBase.GenReserveListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenInvoiceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenInvoiceListResponse GenInvoiceList(ApiPrice.TreolanBase.GenInvoiceListRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenInvoiceList", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenInvoiceListResponse> GenInvoiceListAsync(ApiPrice.TreolanBase.GenInvoiceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenSchetList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenSchetListResponse GenSchetList(ApiPrice.TreolanBase.GenSchetListRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenSchetList", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenSchetListResponse> GenSchetListAsync(ApiPrice.TreolanBase.GenSchetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenSchet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenSchetResponse GenSchet(ApiPrice.TreolanBase.GenSchetRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenSchet", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenSchetResponse> GenSchetAsync(ApiPrice.TreolanBase.GenSchetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenSchetV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenSchetV2Response GenSchetV2(ApiPrice.TreolanBase.GenSchetV2Request request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenSchetV2", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenSchetV2Response> GenSchetV2Async(ApiPrice.TreolanBase.GenSchetV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GetPayers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GetPayersResponse GetPayers(ApiPrice.TreolanBase.GetPayersRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GetPayers", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GetPayersResponse> GetPayersAsync(ApiPrice.TreolanBase.GetPayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.AvailablePrefixes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.AvailablePrefixesResponse AvailablePrefixes(ApiPrice.TreolanBase.AvailablePrefixesRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.AvailablePrefixes", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.AvailablePrefixesResponse> AvailablePrefixesAsync(ApiPrice.TreolanBase.AvailablePrefixesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.ChangeQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.ChangeQueryResponse ChangeQuery(ApiPrice.TreolanBase.ChangeQueryRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.ChangeQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.ChangeQueryResponse> ChangeQueryAsync(ApiPrice.TreolanBase.ChangeQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.ChangeSchet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.ChangeSchetResponse ChangeSchet(ApiPrice.TreolanBase.ChangeSchetRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.ChangeSchet", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.ChangeSchetResponse> ChangeSchetAsync(ApiPrice.TreolanBase.ChangeSchetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.NewOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.NewOrderResponse NewOrder(ApiPrice.TreolanBase.NewOrderRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.NewOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.NewOrderResponse> NewOrderAsync(ApiPrice.TreolanBase.NewOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenOrderResponse GenOrder(ApiPrice.TreolanBase.GenOrderRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenOrderResponse> GenOrderAsync(ApiPrice.TreolanBase.GenOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenQueryResponse GenQuery(ApiPrice.TreolanBase.GenQueryRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenQueryResponse> GenQueryAsync(ApiPrice.TreolanBase.GenQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenChangeSchet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenChangeSchetResponse GenChangeSchet(ApiPrice.TreolanBase.GenChangeSchetRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenChangeSchet", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenChangeSchetResponse> GenChangeSchetAsync(ApiPrice.TreolanBase.GenChangeSchetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenPayerList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenPayerListResponse GenPayerList(ApiPrice.TreolanBase.GenPayerListRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenPayerList", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenPayerListResponse> GenPayerListAsync(ApiPrice.TreolanBase.GenPayerListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCargo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenCargoResponse GenCargo(ApiPrice.TreolanBase.GenCargoRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCargo", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCargoResponse> GenCargoAsync(ApiPrice.TreolanBase.GenCargoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCargoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenCargoListResponse GenCargoList(ApiPrice.TreolanBase.GenCargoListRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCargoList", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCargoListResponse> GenCargoListAsync(ApiPrice.TreolanBase.GenCargoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCargoListByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ApiPrice.TreolanBase.GenCargoListByStatusResponse GenCargoListByStatus(ApiPrice.TreolanBase.GenCargoListByStatusRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/treolan/action/WebService.GenCargoListByStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCargoListByStatusResponse> GenCargoListByStatusAsync(ApiPrice.TreolanBase.GenCargoListByStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCatalog", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCatalogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int criterion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public bool inArticul;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool inName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public bool inMark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int showNc;
        
        public GenCatalogRequest() {
        }
        
        public GenCatalogRequest(string login, string password, string category, string keywords, int criterion, bool inArticul, bool inName, bool inMark, int showNc) {
            this.login = login;
            this.password = password;
            this.category = category;
            this.keywords = keywords;
            this.criterion = criterion;
            this.inArticul = inArticul;
            this.inName = inName;
            this.inMark = inMark;
            this.showNc = showNc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCatalogResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCatalogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int criterion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool inArticul;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public bool inName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public bool inMark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int showNc;
        
        public GenCatalogResponse() {
        }
        
        public GenCatalogResponse(string Result, string login, string password, string category, string keywords, int criterion, bool inArticul, bool inName, bool inMark, int showNc) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.category = category;
            this.keywords = keywords;
            this.criterion = criterion;
            this.inArticul = inArticul;
            this.inName = inName;
            this.inMark = inMark;
            this.showNc = showNc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCatalogV2", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCatalogV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string vendorid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int criterion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool inArticul;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public bool inName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public bool inMark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int showNc;
        
        public GenCatalogV2Request() {
        }
        
        public GenCatalogV2Request(string login, string password, string category, string vendorid, string keywords, int criterion, bool inArticul, bool inName, bool inMark, int showNc) {
            this.login = login;
            this.password = password;
            this.category = category;
            this.vendorid = vendorid;
            this.keywords = keywords;
            this.criterion = criterion;
            this.inArticul = inArticul;
            this.inName = inName;
            this.inMark = inMark;
            this.showNc = showNc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCatalogV2Response", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCatalogV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string vendorid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int criterion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public bool inArticul;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public bool inName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public bool inMark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public int showNc;
        
        public GenCatalogV2Response() {
        }
        
        public GenCatalogV2Response(string Result, string login, string password, string category, string vendorid, string keywords, int criterion, bool inArticul, bool inName, bool inMark, int showNc) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.category = category;
            this.vendorid = vendorid;
            this.keywords = keywords;
            this.criterion = criterion;
            this.inArticul = inArticul;
            this.inName = inName;
            this.inMark = inMark;
            this.showNc = showNc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenStock", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int section;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int criterion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public bool inArticul;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool inName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public bool inMark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int showNc;
        
        public GenStockRequest() {
        }
        
        public GenStockRequest(string login, string password, int section, string keywords, int criterion, bool inArticul, bool inName, bool inMark, int showNc) {
            this.login = login;
            this.password = password;
            this.section = section;
            this.keywords = keywords;
            this.criterion = criterion;
            this.inArticul = inArticul;
            this.inName = inName;
            this.inMark = inMark;
            this.showNc = showNc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenStockResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int section;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int criterion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public bool inArticul;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public bool inName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public bool inMark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int showNc;
        
        public GenStockResponse() {
        }
        
        public GenStockResponse(string Result, string login, string password, int section, string keywords, int criterion, bool inArticul, bool inName, bool inMark, int showNc) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.section = section;
            this.keywords = keywords;
            this.criterion = criterion;
            this.inArticul = inArticul;
            this.inName = inName;
            this.inMark = inMark;
            this.showNc = showNc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInvoice", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Number;
        
        public GenInvoiceRequest() {
        }
        
        public GenInvoiceRequest(string login, string password, string Number) {
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInvoiceResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Number;
        
        public GenInvoiceResponse() {
        }
        
        public GenInvoiceResponse(string Result, string login, string password, string Number) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenReserveList", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenReserveListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GenReserveListRequest() {
        }
        
        public GenReserveListRequest(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenReserveListResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenReserveListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public GenReserveListResponse() {
        }
        
        public GenReserveListResponse(string Result, string login, string password) {
            this.Result = Result;
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInvoiceList", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenInvoiceListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string DateBeg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string DateEnd;
        
        public GenInvoiceListRequest() {
        }
        
        public GenInvoiceListRequest(string login, string password, string DateBeg, string DateEnd) {
            this.login = login;
            this.password = password;
            this.DateBeg = DateBeg;
            this.DateEnd = DateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInvoiceListResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenInvoiceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string DateBeg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string DateEnd;
        
        public GenInvoiceListResponse() {
        }
        
        public GenInvoiceListResponse(string Result, string login, string password, string DateBeg, string DateEnd) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.DateBeg = DateBeg;
            this.DateEnd = DateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenSchetList", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenSchetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string DateBeg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string DateEnd;
        
        public GenSchetListRequest() {
        }
        
        public GenSchetListRequest(string login, string password, string DateBeg, string DateEnd) {
            this.login = login;
            this.password = password;
            this.DateBeg = DateBeg;
            this.DateEnd = DateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenSchetListResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenSchetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string DateBeg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string DateEnd;
        
        public GenSchetListResponse() {
        }
        
        public GenSchetListResponse(string Result, string login, string password, string DateBeg, string DateEnd) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.DateBeg = DateBeg;
            this.DateEnd = DateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenSchet", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenSchetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Number;
        
        public GenSchetRequest() {
        }
        
        public GenSchetRequest(string login, string password, string Number) {
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenSchetResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenSchetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Number;
        
        public GenSchetResponse() {
        }
        
        public GenSchetResponse(string Result, string login, string password, string Number) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenSchetV2", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenSchetV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int groupkit;
        
        public GenSchetV2Request() {
        }
        
        public GenSchetV2Request(string login, string password, string Number, int groupkit) {
            this.login = login;
            this.password = password;
            this.Number = Number;
            this.groupkit = groupkit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenSchetV2Response", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenSchetV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int groupkit;
        
        public GenSchetV2Response() {
        }
        
        public GenSchetV2Response(string Result, string login, string password, string Number, int groupkit) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.Number = Number;
            this.groupkit = groupkit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayers", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GetPayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GetPayersRequest() {
        }
        
        public GetPayersRequest(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayersResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GetPayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public GetPayersResponse() {
        }
        
        public GetPayersResponse(string Result, string login, string password) {
            this.Result = Result;
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvailablePrefixes", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class AvailablePrefixesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string paramXml;
        
        public AvailablePrefixesRequest() {
        }
        
        public AvailablePrefixesRequest(string login, string password, string paramXml) {
            this.login = login;
            this.password = password;
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvailablePrefixesResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class AvailablePrefixesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string paramXml;
        
        public AvailablePrefixesResponse() {
        }
        
        public AvailablePrefixesResponse(object Result, string login, string password, string paramXml) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.paramXml = paramXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeQuery", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class ChangeQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlQuery;
        
        public ChangeQueryRequest() {
        }
        
        public ChangeQueryRequest(string login, string password, string xmlQuery) {
            this.login = login;
            this.password = password;
            this.xmlQuery = xmlQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeQueryResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class ChangeQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string xmlQuery;
        
        public ChangeQueryResponse() {
        }
        
        public ChangeQueryResponse(string Result, string login, string password, string xmlQuery) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.xmlQuery = xmlQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSchet", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class ChangeSchetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlQuery;
        
        public ChangeSchetRequest() {
        }
        
        public ChangeSchetRequest(string login, string password, string xmlQuery) {
            this.login = login;
            this.password = password;
            this.xmlQuery = xmlQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSchetResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class ChangeSchetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string xmlQuery;
        
        public ChangeSchetResponse() {
        }
        
        public ChangeSchetResponse(string Result, string login, string password, string xmlQuery) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.xmlQuery = xmlQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewOrder", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class NewOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string orderXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public short useCode;
        
        public NewOrderRequest() {
        }
        
        public NewOrderRequest(string login, string password, string orderXml, short useCode) {
            this.login = login;
            this.password = password;
            this.orderXml = orderXml;
            this.useCode = useCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewOrderResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class NewOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string orderXml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public short useCode;
        
        public NewOrderResponse() {
        }
        
        public NewOrderResponse(string Result, string login, string password, string orderXml, short useCode) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.orderXml = orderXml;
            this.useCode = useCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenOrder", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int Number;
        
        public GenOrderRequest() {
        }
        
        public GenOrderRequest(string login, string password, int Number) {
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenOrderResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int Number;
        
        public GenOrderResponse() {
        }
        
        public GenOrderResponse(string Result, string login, string password, int Number) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenQuery", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int Number;
        
        public GenQueryRequest() {
        }
        
        public GenQueryRequest(string login, string password, int Number) {
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenQueryResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int Number;
        
        public GenQueryResponse() {
        }
        
        public GenQueryResponse(string Result, string login, string password, int Number) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenChangeSchet", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenChangeSchetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string stringXml;
        
        public GenChangeSchetRequest() {
        }
        
        public GenChangeSchetRequest(string login, string password, string stringXml) {
            this.login = login;
            this.password = password;
            this.stringXml = stringXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenChangeSchetResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenChangeSchetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string stringXml;
        
        public GenChangeSchetResponse() {
        }
        
        public GenChangeSchetResponse(string Result, string login, string password, string stringXml) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.stringXml = stringXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenPayerList", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenPayerListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public GenPayerListRequest() {
        }
        
        public GenPayerListRequest(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenPayerListResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenPayerListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public GenPayerListResponse() {
        }
        
        public GenPayerListResponse(string Result, string login, string password) {
            this.Result = Result;
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCargo", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCargoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int numb;
        
        public GenCargoRequest() {
        }
        
        public GenCargoRequest(string login, string password, int numb) {
            this.login = login;
            this.password = password;
            this.numb = numb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCargoResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCargoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int numb;
        
        public GenCargoResponse() {
        }
        
        public GenCargoResponse(string Result, string login, string password, int numb) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.numb = numb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCargoList", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCargoListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string DateBeg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string DateEnd;
        
        public GenCargoListRequest() {
        }
        
        public GenCargoListRequest(string login, string password, string DateBeg, string DateEnd) {
            this.login = login;
            this.password = password;
            this.DateBeg = DateBeg;
            this.DateEnd = DateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCargoListResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCargoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string DateBeg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string DateEnd;
        
        public GenCargoListResponse() {
        }
        
        public GenCargoListResponse(string Result, string login, string password, string DateBeg, string DateEnd) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.DateBeg = DateBeg;
            this.DateEnd = DateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCargoListByStatus", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCargoListByStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public short status;
        
        public GenCargoListByStatusRequest() {
        }
        
        public GenCargoListByStatusRequest(string login, string password, short status) {
            this.login = login;
            this.password = password;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenCargoListByStatusResponse", WrapperNamespace="http://tempuri.org/treolan/message/", IsWrapped=true)]
    public partial class GenCargoListByStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public short status;
        
        public GenCargoListByStatusResponse() {
        }
        
        public GenCargoListByStatusResponse(string Result, string login, string password, short status) {
            this.Result = Result;
            this.login = login;
            this.password = password;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapPortChannel : ApiPrice.TreolanBase.WebServiceSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapPortClient : System.ServiceModel.ClientBase<ApiPrice.TreolanBase.WebServiceSoapPort>, ApiPrice.TreolanBase.WebServiceSoapPort {
        
        public WebServiceSoapPortClient() {
        }
        
        public WebServiceSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenCatalogResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenCatalog(ApiPrice.TreolanBase.GenCatalogRequest request) {
            return base.Channel.GenCatalog(request);
        }
        
        public string GenCatalog(ref string login, ref string password, ref string category, ref string keywords, ref int criterion, ref bool inArticul, ref bool inName, ref bool inMark, ref int showNc) {
            ApiPrice.TreolanBase.GenCatalogRequest inValue = new ApiPrice.TreolanBase.GenCatalogRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.category = category;
            inValue.keywords = keywords;
            inValue.criterion = criterion;
            inValue.inArticul = inArticul;
            inValue.inName = inName;
            inValue.inMark = inMark;
            inValue.showNc = showNc;
            ApiPrice.TreolanBase.GenCatalogResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenCatalog(inValue);
            login = retVal.login;
            password = retVal.password;
            category = retVal.category;
            keywords = retVal.keywords;
            criterion = retVal.criterion;
            inArticul = retVal.inArticul;
            inName = retVal.inName;
            inMark = retVal.inMark;
            showNc = retVal.showNc;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCatalogResponse> GenCatalogAsync(ApiPrice.TreolanBase.GenCatalogRequest request) {
            return base.Channel.GenCatalogAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenCatalogV2Response ApiPrice.TreolanBase.WebServiceSoapPort.GenCatalogV2(ApiPrice.TreolanBase.GenCatalogV2Request request) {
            return base.Channel.GenCatalogV2(request);
        }
        
        public string GenCatalogV2(ref string login, ref string password, ref string category, ref string vendorid, ref string keywords, ref int criterion, ref bool inArticul, ref bool inName, ref bool inMark, ref int showNc) {
            ApiPrice.TreolanBase.GenCatalogV2Request inValue = new ApiPrice.TreolanBase.GenCatalogV2Request();
            inValue.login = login;
            inValue.password = password;
            inValue.category = category;
            inValue.vendorid = vendorid;
            inValue.keywords = keywords;
            inValue.criterion = criterion;
            inValue.inArticul = inArticul;
            inValue.inName = inName;
            inValue.inMark = inMark;
            inValue.showNc = showNc;
            ApiPrice.TreolanBase.GenCatalogV2Response retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenCatalogV2(inValue);
            login = retVal.login;
            password = retVal.password;
            category = retVal.category;
            vendorid = retVal.vendorid;
            keywords = retVal.keywords;
            criterion = retVal.criterion;
            inArticul = retVal.inArticul;
            inName = retVal.inName;
            inMark = retVal.inMark;
            showNc = retVal.showNc;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCatalogV2Response> GenCatalogV2Async(ApiPrice.TreolanBase.GenCatalogV2Request request) {
            return base.Channel.GenCatalogV2Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenStockResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenStock(ApiPrice.TreolanBase.GenStockRequest request) {
            return base.Channel.GenStock(request);
        }
        
        public string GenStock(ref string login, ref string password, ref int section, ref string keywords, ref int criterion, ref bool inArticul, ref bool inName, ref bool inMark, ref int showNc) {
            ApiPrice.TreolanBase.GenStockRequest inValue = new ApiPrice.TreolanBase.GenStockRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.section = section;
            inValue.keywords = keywords;
            inValue.criterion = criterion;
            inValue.inArticul = inArticul;
            inValue.inName = inName;
            inValue.inMark = inMark;
            inValue.showNc = showNc;
            ApiPrice.TreolanBase.GenStockResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenStock(inValue);
            login = retVal.login;
            password = retVal.password;
            section = retVal.section;
            keywords = retVal.keywords;
            criterion = retVal.criterion;
            inArticul = retVal.inArticul;
            inName = retVal.inName;
            inMark = retVal.inMark;
            showNc = retVal.showNc;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenStockResponse> GenStockAsync(ApiPrice.TreolanBase.GenStockRequest request) {
            return base.Channel.GenStockAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenInvoiceResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenInvoice(ApiPrice.TreolanBase.GenInvoiceRequest request) {
            return base.Channel.GenInvoice(request);
        }
        
        public string GenInvoice(ref string login, ref string password, ref string Number) {
            ApiPrice.TreolanBase.GenInvoiceRequest inValue = new ApiPrice.TreolanBase.GenInvoiceRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.Number = Number;
            ApiPrice.TreolanBase.GenInvoiceResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenInvoice(inValue);
            login = retVal.login;
            password = retVal.password;
            Number = retVal.Number;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenInvoiceResponse> GenInvoiceAsync(ApiPrice.TreolanBase.GenInvoiceRequest request) {
            return base.Channel.GenInvoiceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenReserveListResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenReserveList(ApiPrice.TreolanBase.GenReserveListRequest request) {
            return base.Channel.GenReserveList(request);
        }
        
        public string GenReserveList(ref string login, ref string password) {
            ApiPrice.TreolanBase.GenReserveListRequest inValue = new ApiPrice.TreolanBase.GenReserveListRequest();
            inValue.login = login;
            inValue.password = password;
            ApiPrice.TreolanBase.GenReserveListResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenReserveList(inValue);
            login = retVal.login;
            password = retVal.password;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenReserveListResponse> GenReserveListAsync(ApiPrice.TreolanBase.GenReserveListRequest request) {
            return base.Channel.GenReserveListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenInvoiceListResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenInvoiceList(ApiPrice.TreolanBase.GenInvoiceListRequest request) {
            return base.Channel.GenInvoiceList(request);
        }
        
        public string GenInvoiceList(ref string login, ref string password, ref string DateBeg, ref string DateEnd) {
            ApiPrice.TreolanBase.GenInvoiceListRequest inValue = new ApiPrice.TreolanBase.GenInvoiceListRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.DateBeg = DateBeg;
            inValue.DateEnd = DateEnd;
            ApiPrice.TreolanBase.GenInvoiceListResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenInvoiceList(inValue);
            login = retVal.login;
            password = retVal.password;
            DateBeg = retVal.DateBeg;
            DateEnd = retVal.DateEnd;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenInvoiceListResponse> GenInvoiceListAsync(ApiPrice.TreolanBase.GenInvoiceListRequest request) {
            return base.Channel.GenInvoiceListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenSchetListResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenSchetList(ApiPrice.TreolanBase.GenSchetListRequest request) {
            return base.Channel.GenSchetList(request);
        }
        
        public string GenSchetList(ref string login, ref string password, ref string DateBeg, ref string DateEnd) {
            ApiPrice.TreolanBase.GenSchetListRequest inValue = new ApiPrice.TreolanBase.GenSchetListRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.DateBeg = DateBeg;
            inValue.DateEnd = DateEnd;
            ApiPrice.TreolanBase.GenSchetListResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenSchetList(inValue);
            login = retVal.login;
            password = retVal.password;
            DateBeg = retVal.DateBeg;
            DateEnd = retVal.DateEnd;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenSchetListResponse> GenSchetListAsync(ApiPrice.TreolanBase.GenSchetListRequest request) {
            return base.Channel.GenSchetListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenSchetResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenSchet(ApiPrice.TreolanBase.GenSchetRequest request) {
            return base.Channel.GenSchet(request);
        }
        
        public string GenSchet(ref string login, ref string password, ref string Number) {
            ApiPrice.TreolanBase.GenSchetRequest inValue = new ApiPrice.TreolanBase.GenSchetRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.Number = Number;
            ApiPrice.TreolanBase.GenSchetResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenSchet(inValue);
            login = retVal.login;
            password = retVal.password;
            Number = retVal.Number;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenSchetResponse> GenSchetAsync(ApiPrice.TreolanBase.GenSchetRequest request) {
            return base.Channel.GenSchetAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenSchetV2Response ApiPrice.TreolanBase.WebServiceSoapPort.GenSchetV2(ApiPrice.TreolanBase.GenSchetV2Request request) {
            return base.Channel.GenSchetV2(request);
        }
        
        public string GenSchetV2(ref string login, ref string password, ref string Number, ref int groupkit) {
            ApiPrice.TreolanBase.GenSchetV2Request inValue = new ApiPrice.TreolanBase.GenSchetV2Request();
            inValue.login = login;
            inValue.password = password;
            inValue.Number = Number;
            inValue.groupkit = groupkit;
            ApiPrice.TreolanBase.GenSchetV2Response retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenSchetV2(inValue);
            login = retVal.login;
            password = retVal.password;
            Number = retVal.Number;
            groupkit = retVal.groupkit;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenSchetV2Response> GenSchetV2Async(ApiPrice.TreolanBase.GenSchetV2Request request) {
            return base.Channel.GenSchetV2Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GetPayersResponse ApiPrice.TreolanBase.WebServiceSoapPort.GetPayers(ApiPrice.TreolanBase.GetPayersRequest request) {
            return base.Channel.GetPayers(request);
        }
        
        public string GetPayers(ref string login, ref string password) {
            ApiPrice.TreolanBase.GetPayersRequest inValue = new ApiPrice.TreolanBase.GetPayersRequest();
            inValue.login = login;
            inValue.password = password;
            ApiPrice.TreolanBase.GetPayersResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GetPayers(inValue);
            login = retVal.login;
            password = retVal.password;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GetPayersResponse> GetPayersAsync(ApiPrice.TreolanBase.GetPayersRequest request) {
            return base.Channel.GetPayersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.AvailablePrefixesResponse ApiPrice.TreolanBase.WebServiceSoapPort.AvailablePrefixes(ApiPrice.TreolanBase.AvailablePrefixesRequest request) {
            return base.Channel.AvailablePrefixes(request);
        }
        
        public object AvailablePrefixes(ref string login, ref string password, ref string paramXml) {
            ApiPrice.TreolanBase.AvailablePrefixesRequest inValue = new ApiPrice.TreolanBase.AvailablePrefixesRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.paramXml = paramXml;
            ApiPrice.TreolanBase.AvailablePrefixesResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).AvailablePrefixes(inValue);
            login = retVal.login;
            password = retVal.password;
            paramXml = retVal.paramXml;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.AvailablePrefixesResponse> AvailablePrefixesAsync(ApiPrice.TreolanBase.AvailablePrefixesRequest request) {
            return base.Channel.AvailablePrefixesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.ChangeQueryResponse ApiPrice.TreolanBase.WebServiceSoapPort.ChangeQuery(ApiPrice.TreolanBase.ChangeQueryRequest request) {
            return base.Channel.ChangeQuery(request);
        }
        
        public string ChangeQuery(ref string login, ref string password, ref string xmlQuery) {
            ApiPrice.TreolanBase.ChangeQueryRequest inValue = new ApiPrice.TreolanBase.ChangeQueryRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.xmlQuery = xmlQuery;
            ApiPrice.TreolanBase.ChangeQueryResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).ChangeQuery(inValue);
            login = retVal.login;
            password = retVal.password;
            xmlQuery = retVal.xmlQuery;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.ChangeQueryResponse> ChangeQueryAsync(ApiPrice.TreolanBase.ChangeQueryRequest request) {
            return base.Channel.ChangeQueryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.ChangeSchetResponse ApiPrice.TreolanBase.WebServiceSoapPort.ChangeSchet(ApiPrice.TreolanBase.ChangeSchetRequest request) {
            return base.Channel.ChangeSchet(request);
        }
        
        public string ChangeSchet(ref string login, ref string password, ref string xmlQuery) {
            ApiPrice.TreolanBase.ChangeSchetRequest inValue = new ApiPrice.TreolanBase.ChangeSchetRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.xmlQuery = xmlQuery;
            ApiPrice.TreolanBase.ChangeSchetResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).ChangeSchet(inValue);
            login = retVal.login;
            password = retVal.password;
            xmlQuery = retVal.xmlQuery;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.ChangeSchetResponse> ChangeSchetAsync(ApiPrice.TreolanBase.ChangeSchetRequest request) {
            return base.Channel.ChangeSchetAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.NewOrderResponse ApiPrice.TreolanBase.WebServiceSoapPort.NewOrder(ApiPrice.TreolanBase.NewOrderRequest request) {
            return base.Channel.NewOrder(request);
        }
        
        public string NewOrder(ref string login, ref string password, ref string orderXml, ref short useCode) {
            ApiPrice.TreolanBase.NewOrderRequest inValue = new ApiPrice.TreolanBase.NewOrderRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.orderXml = orderXml;
            inValue.useCode = useCode;
            ApiPrice.TreolanBase.NewOrderResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).NewOrder(inValue);
            login = retVal.login;
            password = retVal.password;
            orderXml = retVal.orderXml;
            useCode = retVal.useCode;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.NewOrderResponse> NewOrderAsync(ApiPrice.TreolanBase.NewOrderRequest request) {
            return base.Channel.NewOrderAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenOrderResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenOrder(ApiPrice.TreolanBase.GenOrderRequest request) {
            return base.Channel.GenOrder(request);
        }
        
        public string GenOrder(ref string login, ref string password, ref int Number) {
            ApiPrice.TreolanBase.GenOrderRequest inValue = new ApiPrice.TreolanBase.GenOrderRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.Number = Number;
            ApiPrice.TreolanBase.GenOrderResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenOrder(inValue);
            login = retVal.login;
            password = retVal.password;
            Number = retVal.Number;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenOrderResponse> GenOrderAsync(ApiPrice.TreolanBase.GenOrderRequest request) {
            return base.Channel.GenOrderAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenQueryResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenQuery(ApiPrice.TreolanBase.GenQueryRequest request) {
            return base.Channel.GenQuery(request);
        }
        
        public string GenQuery(ref string login, ref string password, ref int Number) {
            ApiPrice.TreolanBase.GenQueryRequest inValue = new ApiPrice.TreolanBase.GenQueryRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.Number = Number;
            ApiPrice.TreolanBase.GenQueryResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenQuery(inValue);
            login = retVal.login;
            password = retVal.password;
            Number = retVal.Number;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenQueryResponse> GenQueryAsync(ApiPrice.TreolanBase.GenQueryRequest request) {
            return base.Channel.GenQueryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenChangeSchetResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenChangeSchet(ApiPrice.TreolanBase.GenChangeSchetRequest request) {
            return base.Channel.GenChangeSchet(request);
        }
        
        public string GenChangeSchet(ref string login, ref string password, ref string stringXml) {
            ApiPrice.TreolanBase.GenChangeSchetRequest inValue = new ApiPrice.TreolanBase.GenChangeSchetRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.stringXml = stringXml;
            ApiPrice.TreolanBase.GenChangeSchetResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenChangeSchet(inValue);
            login = retVal.login;
            password = retVal.password;
            stringXml = retVal.stringXml;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenChangeSchetResponse> GenChangeSchetAsync(ApiPrice.TreolanBase.GenChangeSchetRequest request) {
            return base.Channel.GenChangeSchetAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenPayerListResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenPayerList(ApiPrice.TreolanBase.GenPayerListRequest request) {
            return base.Channel.GenPayerList(request);
        }
        
        public string GenPayerList(ref string login, ref string password) {
            ApiPrice.TreolanBase.GenPayerListRequest inValue = new ApiPrice.TreolanBase.GenPayerListRequest();
            inValue.login = login;
            inValue.password = password;
            ApiPrice.TreolanBase.GenPayerListResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenPayerList(inValue);
            login = retVal.login;
            password = retVal.password;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenPayerListResponse> GenPayerListAsync(ApiPrice.TreolanBase.GenPayerListRequest request) {
            return base.Channel.GenPayerListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenCargoResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenCargo(ApiPrice.TreolanBase.GenCargoRequest request) {
            return base.Channel.GenCargo(request);
        }
        
        public string GenCargo(ref string login, ref string password, ref int numb) {
            ApiPrice.TreolanBase.GenCargoRequest inValue = new ApiPrice.TreolanBase.GenCargoRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.numb = numb;
            ApiPrice.TreolanBase.GenCargoResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenCargo(inValue);
            login = retVal.login;
            password = retVal.password;
            numb = retVal.numb;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCargoResponse> GenCargoAsync(ApiPrice.TreolanBase.GenCargoRequest request) {
            return base.Channel.GenCargoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenCargoListResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenCargoList(ApiPrice.TreolanBase.GenCargoListRequest request) {
            return base.Channel.GenCargoList(request);
        }
        
        public string GenCargoList(ref string login, ref string password, ref string DateBeg, ref string DateEnd) {
            ApiPrice.TreolanBase.GenCargoListRequest inValue = new ApiPrice.TreolanBase.GenCargoListRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.DateBeg = DateBeg;
            inValue.DateEnd = DateEnd;
            ApiPrice.TreolanBase.GenCargoListResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenCargoList(inValue);
            login = retVal.login;
            password = retVal.password;
            DateBeg = retVal.DateBeg;
            DateEnd = retVal.DateEnd;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCargoListResponse> GenCargoListAsync(ApiPrice.TreolanBase.GenCargoListRequest request) {
            return base.Channel.GenCargoListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApiPrice.TreolanBase.GenCargoListByStatusResponse ApiPrice.TreolanBase.WebServiceSoapPort.GenCargoListByStatus(ApiPrice.TreolanBase.GenCargoListByStatusRequest request) {
            return base.Channel.GenCargoListByStatus(request);
        }
        
        public string GenCargoListByStatus(ref string login, ref string password, ref short status) {
            ApiPrice.TreolanBase.GenCargoListByStatusRequest inValue = new ApiPrice.TreolanBase.GenCargoListByStatusRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.status = status;
            ApiPrice.TreolanBase.GenCargoListByStatusResponse retVal = ((ApiPrice.TreolanBase.WebServiceSoapPort)(this)).GenCargoListByStatus(inValue);
            login = retVal.login;
            password = retVal.password;
            status = retVal.status;
            return retVal.Result;
        }
        
        public System.Threading.Tasks.Task<ApiPrice.TreolanBase.GenCargoListByStatusResponse> GenCargoListByStatusAsync(ApiPrice.TreolanBase.GenCargoListByStatusRequest request) {
            return base.Channel.GenCargoListByStatusAsync(request);
        }
    }
}
