//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_meet_links
    {
        public int id { get; set; }
        public int id_document { get; set; }
        public Nullable<int> id_department { get; set; }
        public Nullable<int> id_position { get; set; }
        public Nullable<int> id_employee { get; set; }
        public System.DateTime dattim1 { get; set; }
        public string creator_sid { get; set; }
        public bool enabled { get; set; }
        public System.DateTime dattim2 { get; set; }
        public string deleter_sid { get; set; }
    }
}
