//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_folders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public document_folders()
        {
            this.document_folders1 = new HashSet<document_folders>();
            this.documents = new HashSet<documents>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string creator_sid { get; set; }
        public System.DateTime create_date { get; set; }
        public bool enabled { get; set; }
        public string deleter_sid { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public Nullable<int> parent_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document_folders> document_folders1 { get; set; }
        public virtual document_folders document_folders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documents> documents { get; set; }
    }
}
