//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_transfers
    {
        public int id { get; set; }
        public int id_employee { get; set; }
        public int id_vacancy { get; set; }
        public int id_position_from { get; set; }
        public int id_department_from { get; set; }
        public int id_position_to { get; set; }
        public int id_department_to { get; set; }
        public System.DateTime dattim1 { get; set; }
        public string creator_sid { get; set; }
    }
}
