//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_question_form_recomandations
    {
        public int id { get; set; }
        public string sid { get; set; }
        public int id_question_form { get; set; }
        public bool enabled { get; set; }
        public System.DateTime dattim1 { get; set; }
        public string name { get; set; }
        public string organization { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
    }
}
