//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_selection_state_history_report
    {
        public int id_selection { get; set; }
        public int id_state { get; set; }
        public System.DateTime create_date { get; set; }
        public string state_name { get; set; }
    }
}
