//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_invite_messages
    {
        public int id { get; set; }
        public int city_id { get; set; }
        public string text { get; set; }
        public string map_photo { get; set; }
        public System.DateTime date_change { get; set; }
        public string changer_sid { get; set; }
        public bool enabled { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public string deleter_sid { get; set; }
    
        public virtual cities cities { get; set; }
    }
}
