//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_question_links
    {
        public int id { get; set; }
        public int id_selection { get; set; }
        public System.Guid sid { get; set; }
        public bool enabled { get; set; }
        public System.DateTime dattim1 { get; set; }
        public string creator_sid { get; set; }
        public System.DateTime dattim2 { get; set; }
        public string deleter_sid { get; set; }
        public bool sended { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public string sender_sid { get; set; }
    }
}
