//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_candidate_resume_files
    {
        public int id { get; set; }
        public int id_candidate { get; set; }
        public System.Guid sid { get; set; }
        public byte[] data { get; set; }
        public System.DateTime dattim1 { get; set; }
        public string creator_sid { get; set; }
        public string file_name { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<System.DateTime> dattim2 { get; set; }
        public string deleter_sid { get; set; }
    }
}
