//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_question_form_facts
    {
        public int id { get; set; }
        public int form_id { get; set; }
        public System.DateTime dattim1 { get; set; }
        public Nullable<int> rate { get; set; }
        public int fact_id { get; set; }
    }
}
