//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_question_facts
    {
        public int id { get; set; }
        public string name { get; set; }
        public int order_num { get; set; }
        public bool enabled { get; set; }
        public int column_num { get; set; }
    }
}
