//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruit_employee_change_reminders
    {
        public int id { get; set; }
        public int id_employee { get; set; }
        public System.DateTime date_change { get; set; }
        public bool send { get; set; }
        public int id_vacancy { get; set; }
        public int id_department { get; set; }
        public int id_position { get; set; }
        public bool enabled { get; set; }
        public string creator_sid { get; set; }
        public System.DateTime dattim1 { get; set; }
        public int id_selection { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
    }
}
