//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHistory
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int RequestOldStatusId { get; set; }
        public int RequestNewStatusId { get; set; }
        public string CrteatorSid { get; set; }
        public System.DateTime Date { get; set; }
        public int RequestHistoryActionId { get; set; }
        public Nullable<System.Guid> AgreementDocumentUid { get; set; }
        public Nullable<int> AgreementId { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual RequestStatuses RequestStatuses { get; set; }
        public virtual RequestStatuses RequestStatuses1 { get; set; }
    }
}
