//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public int SchemaId { get; set; }
        public string TestClassName { get; set; }
        public int ObjectId { get; set; }
        public string Name { get; set; }
    }
}
