//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor_state_pictures
    {
        public int id { get; set; }
        public int id_vendor_state { get; set; }
        public byte[] file_data { get; set; }
        public bool enabled { get; set; }
        public System.Guid file_fuid { get; set; }
        public string file_name { get; set; }
    }
}
